name: build

on:
  push:
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: sudo mvn  -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dgpg.skip -P all clean install --file pom.xml

    - name: Integration Tests
      run: sudo mvn -Dmaven.javadoc.skip=true -Dgpg.skip -P integration-tests-only clean verify --file pom.xml
