name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: sudo mvn clean package -Pall -X -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dgpg.skip --file pom.xml

    - name: Integration Tests
      run: sudo mvn clean package -X -Pintegration-tests-only -Dmaven.javadoc.skip=true -Dgpg.skip --file pom.xml
