name: plugin-test

on:
  push:
    paths-ignore:
      - '**.md'
jobs:
  # TODO 后面可以分每个插件使用一个job并且yml配置文件分开
  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Agent with Maven
      run: sudo mvn clean install -Pagent -Dmaven.javadoc.skip=true -Dgpg.skip -Dmaven.test.skip=true -f pom.xml

    - name: Build Integration Tests with Maven
      run: sudo mvn clean install -Dbuild.skip.test=true -P integration-tests-only -f pom.xml

    - name: Test Jedis Plugin (3.0.0~3.3.0)
      run: |
        versions=("3.0.0" "3.3.0")
        for version in ${versions[@]}
        do
          echo Start to test jedis-$version
          sudo mvn -Dmaven.javadoc.skip=true -Dgpg.skip -Djedis.version=$version -P integration-tests-only -pl :jedis-tests clean verify -f pom.xml
        done

    - name: Test Apache Dubbo Plugin (2.7.3)
      run: |
        versions=("2.7.3")
        for version in ${versions[@]}
        do
          echo Start to test apache-dubbo-$version
          sudo mvn -Dmaven.javadoc.skip=true -Dgpg.skip -Ddubbo.version=$version -P integration-tests-only -pl :apache-dubbo-tests clean verify -f pom.xml
        done

    - name: Test HttpClient Plugin (4.3.6)
      run: |
        versions=("4.3.6")
        for version in ${versions[@]}
        do
          echo Start to test httpclient-$version
          sudo mvn -Dmaven.javadoc.skip=true -Dgpg.skip -Dhttpclient.version=$version -P integration-tests-only -pl :httpclient-tests clean verify -f pom.xml
        done

    - name: Test Jdbc Plugin (6.0.6)
      run: |
        versions=("6.0.6")
        for version in ${versions[@]}
        do
          echo Start to test mysql-connector-java-$version
          sudo mvn -Dmaven.javadoc.skip=true -Dgpg.skip -Dmysql-connector-java.version=$version -P integration-tests-only -pl :mysql-jdbc-tests clean verify -f pom.xml
        done

    - name: Test Okhttp Plugin (3.12.0)
      run: |
        versions=("3.12.0")
        for version in ${versions[@]}
        do
          echo Start to test okhttp-$version
          sudo mvn -Dmaven.javadoc.skip=true -Dgpg.skip -Dokhttp.version=$version -P integration-tests-only -pl :okhttp-tests clean verify -f pom.xml
        done
